### ISSUE TITLE
Borg theme hides description text on the user registration page

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/borg#31]
On the user registration page, any "description" text for a field is not displayed (there is CSS in components.css that sets it to `display: none`). This has the effect of hiding the useful information about the Username and Email address, as well as any description text in other fields that might be on that page.

Addressing the issue is not as simple as just removing that CSS, because restoring the description messes up the widths of the text boxes.

This can be seen on any of the backdropcms.org user registration pages, by going into the browser and clearing the CSS that hides the description fields. Example below from backdropcms.org: left is the current state, right is with the `display:none` commented out.

![no_description](https://user-images.githubusercontent.com/29214084/159576780-f314287e-669e-42a4-b1b0-f343b7164263.jpg)

**Comment by jenlampton** [comment]
There wasn't any useful text for username and password, which is why the description was hidden, but you are correct that we should not do that with CSS. It would be better as a `form_alter()` to remove the useless text :)  That way other actually useful text can still be seen!!

Yes please to this change :)

**Comment by jenlampton** [comment]
This change has been committed and will be included in the next release.
